name: Ruby Theme Deploy
on:
  push:
    branches:
      - clairerougie
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: TryGhost/action-deploy-theme@v1.6.3
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
